name: lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install --with lint

    - name: flake8
      run: poetry run flake8 --verbose --config .flake8 src/

    - name: black
      run: poetry run black src/ --check --line-length 79
